const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');
const { encrypt, decrypt } = require('../utils/encryption');

const GitRepository = sequelize.define('GitRepository', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Friendly name for the repository'
  },
  provider: {
    type: DataTypes.ENUM('github', 'gitlab', 'gitea', 'bitbucket'),
    allowNull: false,
    comment: 'Git hosting provider'
  },
  repository_url: {
    type: DataTypes.STRING,
    allowNull: false,
    comment: 'Git repository URL (HTTPS)'
  },
  branch: {
    type: DataTypes.STRING,
    defaultValue: 'main',
    comment: 'Branch to use for commits and sync'
  },
  access_token: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Encrypted access token for authentication'
  },
  ssh_key: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Encrypted SSH private key (alternative to token)'
  },
  enabled: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    comment: 'Whether this repository is active'
  },
  auto_commit: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    comment: 'Automatically commit configuration changes'
  },
  auto_sync: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'GitOps mode: sync from Git as source of truth'
  },
  sync_interval: {
    type: DataTypes.INTEGER,
    defaultValue: 300,
    comment: 'Sync interval in seconds for GitOps mode'
  },
  last_sync: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Last time config was synced from Git'
  },
  last_commit_sha: {
    type: DataTypes.STRING,
    allowNull: true,
    comment: 'SHA of last commit made or synced'
  },
  commit_message_template: {
    type: DataTypes.TEXT,
    defaultValue: 'chore: update CaddyManager configuration\n\n{{changes}}\n\n🤖 Generated by CaddyManager',
    comment: 'Template for commit messages, supports {{changes}} placeholder'
  }
}, {
  tableName: 'git_repositories',
  timestamps: true
});

// ── Encrypt sensitive fields before persisting ────────────────────────────────
const ENCRYPTED_FIELDS = ['access_token', 'ssh_key'];

function encryptFields(instance) {
  for (const field of ENCRYPTED_FIELDS) {
    if (instance[field]) {
      instance[field] = encrypt(instance[field]);
    }
  }
}

GitRepository.addHook('beforeCreate', encryptFields);

GitRepository.addHook('beforeUpdate', (instance) => {
  for (const field of ENCRYPTED_FIELDS) {
    if (instance.changed(field) && instance[field]) {
      instance[field] = encrypt(instance[field]);
    }
  }
});

// ── Decrypt sensitive fields after reading ────────────────────────────────────
GitRepository.addHook('afterFind', (result) => {
  if (!result) return;
  const items = Array.isArray(result) ? result : [result];
  for (const repo of items) {
    if (!repo) continue;
    for (const field of ENCRYPTED_FIELDS) {
      if (repo[field]) {
        repo[field] = decrypt(repo[field]);
      }
    }
  }
});

module.exports = GitRepository;
