services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    volumes:
      - sqlite_data:/app/data  # Mount SQLite data directory
    ports:
      - "3020:3020"
    depends_on:
      - caddy

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    profiles:
      - "with-postgres"  # Only start when explicitly enabled
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=caddymanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    restart: unless-stopped

volumes:
  sqlite_data:  # Named volume for SQLite database files
  postgres_data:
  caddy_data:
  caddy_config:
